# Generated by Django 2.2.3 on 2020-04-26 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bom_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('wap', models.FloatField()),
                ('volume', models.PositiveIntegerField()),
                ('trades', models.PositiveIntegerField()),
                ('turnover', models.FloatField()),
                ('deliverable_quantity', models.IntegerField()),
                ('percent_del_traded_qty', models.FloatField()),
                ('spread_highLow', models.FloatField()),
                ('spread_closeOpen', models.FloatField()),
                ('rsi', models.FloatField()),
                ('sma_periodSmall', models.FloatField()),
                ('sma_periodBig', models.FloatField()),
                ('bom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Company')),
            ],
            options={
                'unique_together': {('bom_id', 'date')},
            },
        ),
    ]
