# Generated by Django 2.2.3 on 2020-04-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_updated_date',
            field=models.DateField(null=True),
        ),
    ]
