# Generated by Django 2.2.3 on 2020-05-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20200504_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='rsi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='sma_periodBig',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='sma_periodSmall',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
