# Generated by Django 3.0.8 on 2020-07-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20200504_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='period',
            field=models.CharField(choices=[('1M', '1minute'), ('5M', '5minute'), ('15M', '15minute'), ('30M', '30minute'), ('1D', '1 Day')], default='1D', max_length=3),
        ),
        migrations.AlterField(
            model_name='company',
            name='last_updated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
