# Generated by Django 3.0.8 on 2020-07-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20200714_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='yahoo_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
