# Generated by Django 3.0.8 on 2020-07-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20200715_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='last_updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
