# Generated by Django 3.0.8 on 2020-07-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_dailystockstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystockstats',
            name='adx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystockstats',
            name='atr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystockstats',
            name='bol_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystockstats',
            name='bol_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystockstats',
            name='day_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystockstats',
            name='day_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystockstats',
            name='macd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystockstats',
            name='mfi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystockstats',
            name='roc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystockstats',
            name='rsi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystockstats',
            name='sma_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystockstats',
            name='sma_100',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystockstats',
            name='sma_20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystockstats',
            name='sma_200',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystockstats',
            name='sma_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystockstats',
            name='sma_50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystockstats',
            name='stochastic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystockstats',
            name='willr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
