# Generated by Django 3.0.8 on 2020-08-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_dailyprice_weeklyprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprice',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='weeklyprice',
            name='date',
            field=models.DateField(),
        ),
    ]
