# Generated by Django 3.0.8 on 2020-08-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_auto_20200806_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystockstats',
            name='date',
            field=models.DateField(),
        ),
    ]
