# Generated by Django 4.2.20 on 2025-03-30 12:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Stock symbol (e.g., RELIANCE, TCS)",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(1)
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full company name", max_length=100
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        help_text="Industry sector of the stock", max_length=50
                    ),
                ),
                (
                    "is_nifty50",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the stock is part of Nifty 50 index",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date of the price data")),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Opening price",
                        max_digits=10,
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Highest price of the day",
                        max_digits=10,
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Lowest price of the day",
                        max_digits=10,
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Closing price",
                        max_digits=10,
                    ),
                ),
                ("volume", models.BigIntegerField(help_text="Trading volume")),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="stock.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price History",
                "verbose_name_plural": "Price Histories",
                "ordering": ["-date"],
                "unique_together": {("stock", "date")},
            },
        ),
    ]
