# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 15:17
from __future__ import unicode_literals

import datagrab.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datagrab', '0005_auto_20170723_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksymbol',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='E:\\finalproject\\trunk\\tradingstuff\\trading_webapp\\tradingsauce\\csvData'), upload_to=''),
        ),
    ]
