# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datagrab', '0006_auto_20170731_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocksymbol',
            name='file',
        ),
    ]
